name: google_auth
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  iconly: ^1.0.1
  logger: ^1.0.0
  intl: ^0.18.0
  fl_chart: ^0.40.0
  http: ^1.2.2
  firebase_core: ^2.17.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
